name: CI
# touch
on:
  push:
    branches: [master]
    tags: ['**']
  pull_request:

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  ci:
    uses: input-output-hk/catalyst-forge/.github/workflows/ci.yml@fix-docker-setup
    with:
      forge_version: 0.15.0